; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;
;   Envs:
;   - bridge (Sensor Hub / Sender)
;   - web (Gateway / Receiver connected to PC)
;   - remote (Handheld Monitor)
;
;
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0
    bblanchon/ArduinoJson @ ^6.21.3
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^1.2.3

; 1. BRIDGE (Sensor Hub / Miner)
[env:bridge]
build_src_filter = +<bridge.cpp>

; 2. WEB (Gateway / Receiver)
[env:web]
build_src_filter = +<web.cpp>

; 3. REMOTE (Handheld)
[env:remote]
build_src_filter = +<remote.cpp>
